# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-gnome-rocm
description: This is my personal OS image with kernel downgraded for ROCm support.

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

modules:

  # Rimozione dei moduli non necessari per ROCm
  - type: rpm-ostree
    remove:
      - bmi260
      - kmod-bmi260
      - broadcom-wl
      - gpd-fan
      - kmod-gpd-fan
      - kernel-devel-matched
      - kmod-ayaneo-platform
      - ayaneo-platform
      - kmod-ayn-platform
      - ayn-platform
      - kmod-framework-laptop
      - framework-laptop-kmod-common
      - kmod-gcadapter_oc
      - gcadapter_oc
      - kmod-openrazer
      - openrazer-kmod-common
      - kmod-v4l2loopback
      - kmod-wl
      - kvmfr
      - kmod-kvmfr
      - nct6687d
      - kmod-nct6687d
      - ryzen-smu
      - kmod-ryzen-smu
      - v4l2loopback
      - kmod-vhba
      - vhba
      - xone-kmod-common
      - kmod-xone
      - zenergy
      - kmod-zenergy
      - kernel-core
      - kernel-modules-core
      - kernel-modules
      - kernel-modules-extra
      - kernel-devel
      - kernel

  - type: rpm-ostree
    install:
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-devel-6.13.7-108.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-6.13.7-108.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-core-6.13.7-108.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-modules-6.13.7-108.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-modules-core-6.13.7-108.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-modules-extra-6.13.7-108.bazzite.fc42.x86_64.rpm
      - rpm-build
      - rpmdevtools

  - type: custom
    name: install-warp
    source: local
    buildscript: |
      ./live/install_warp.sh
