---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzite-gnome-rocm
description: This is my personal OS image with kernel downgraded for ROCm support.

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /tmp/system

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.brave.Browser
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {}

  - type: rpm-ostree
    remove:
      - bmi260
      - kmod-bmi260
      - broadcom-wl
      - gpd-fan
      - kmod-gpd-fan
      - kernel-devel-matched
      - kmod-ayaneo-platform
      - ayaneo-platform
      - kmod-ayn-platform
      - ayn-platform
      - kmod-framework-laptop
      - framework-laptop-kmod-common
      - kmod-gcadapter_oc
      - gcadapter_oc
      - kmod-openrazer
      - openrazer-kmod-common
      - kmod-v4l2loopback
      - kmod-wl
      - kvmfr
      - kmod-kvmfr
      - nct6687d
      - kmod-nct6687d
      - ryzen-smu
      - kmod-ryzen-smu
      - v4l2loopback
      - kmod-vhba
      - vhba
      - xone-kmod-common
      - kmod-xone
      - zenergy
      - kmod-zenergy
      - kernel-core
      - kernel-modules-core
      - kernel-modules
      - kernel-modules-extra
      - kernel-devel
      - kernel

  - type: rpm-ostree
    install:
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-devel-6.13.7-108.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-6.13.7-108.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-core-6.13.7-108.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-modules-6.13.7-108.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-modules-core-6.13.7-108.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-108.1/kernel-modules-extra-6.13.7-108.bazzite.fc42.x86_64.rpm

  - type: copy
    from: ghcr.io/ublue-os/akmods-extra:6.13.7-108.bazzite.fc42.x86_64
    src: /rpms/
    dest: /tmp/rpms

  - type: containerfile
    snippets:
      - RUN sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/_copr_ublue-os-akmods.repo
      - RUN find /tmp/rpms
      - RUN rpm-ostree install \
          /tmp/rpms/kmods/*nct6687*.rpm \
          /tmp/rpms/kmods/*xone*.rpm \
          /tmp/rpms/kmods/*zenergy*.rpm \
          /tmp/rpms/kmods/*v4l2loopback*.rpm \
          /tmp/rpms/kmods/*vhba*.rpm \
          /tmp/rpms/kmods/*ryzen-smu*.rpm \
          /tmp/rpms/kmods/*openrazer*.rpm \
          /tmp/rpms/kmods/*gcadapter_oc*.rpm \
          /tmp/rpms/kmods/*framework-laptop*.rpm \
          /tmp/rpms/kmods/*ayn-platform*.rpm \
          /tmp/rpms/kmods/*ayaneo-platform*.rpm \
          /tmp/rpms/kmods/*gpd-fan*.rpm \
          /tmp/rpms/kmods/*wl*.rpm \
          /tmp/rpms/kmods/*bmi260*.rpm \
          /tmp/rpms/kmods/*kvmfr*.rpm
